spring.application.name=TarefaORM
spring.datasource.url=jdbc:postgresql://localhost:5433/atividade_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none
