version: "3.9"

volumes:
  postgres_data:
  mongo_data:

services:
  postgres:
    image: postgres:16
    container_name: atividades_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: AtividadesBD
      POSTGRES_USER: atividades_user
      POSTGRES_PASSWORD: atividades_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/01_creates_tables.sql:/docker-entrypoint-initdb.d/01_creates_tables.sql:ro
      - ./sql/02_inserts.sql:/docker-entrypoint-initdb.d/02_inserts.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U atividades_user -d AtividadesBD"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:9
    container_name: atividades_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@atividades.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy

  mongodb:
    image: mongo:6.0
    container_name: atividades_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin_mongo
      MONGO_INITDB_ROOT_PASSWORD: senha_mongo
      MONGO_INITDB_DATABASE: AtividadesProj
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./python_mongo/init_mongo.js:/docker-entrypoint-initdb.d/init_mongo.js:ro
