spring.application.name=SpringDataJpaExample
# Configurações do banco de dados
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Define o tamanho máximo de conexões simultâneas (Padrão é 10)
spring.datasource.hikari.maximum-pool-size=10
# Define o número mínimo de conexões ociosas mantidas pelo pool
spring.datasource.hikari.minimum-idle=5
# Tempo máximo que uma conexão pode ficar ociosa antes de ser descartada (em ms)
spring.datasource.hikari.idle-timeout=30000
# Nome do pool (opcional, ajuda a identificar nos logs)
spring.datasource.hikari.pool-name=SpringDataJpaPool

# Exibe o dialeto e informações de conexão de forma mais verbosa
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Ajuda a preencher o 'Database info' no log do Hibernate
spring.jpa.properties.hibernate.generate_statistics=true
