services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_atividades
    restart: always
    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123

    volumes:
      - mongodb_data:/data/db
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro

volumes:
  mongodb_data: