version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: meu_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: adminjose
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: Atividades_Proj
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: